global:
  scrape_interval:     10s # By default, scrape targets every 10 seconds.
# Scrape configurations containing scrape endpoints
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: pushgateway
    static_configs:
    - targets: ['pushgateway:9091'] 
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: node
    static_configs:
    - targets: ['192.168.102.147:9100']

